//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMProjectWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DMPortalEntities : DbContext
    {
        public DMPortalEntities()
            : base("name=DMPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int aspnet_Membership_GetAllUsers(string applicationName, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var applicationNameParameter = applicationName != null ?
                new ObjectParameter("ApplicationName", applicationName) :
                new ObjectParameter("ApplicationName", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("aspnet_Membership_GetAllUsers", applicationNameParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<S_Duyurularim_Result> S_Duyurularim(Nullable<System.Guid> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Duyurularim_Result>("S_Duyurularim", userIDParameter);
        }
    
        public virtual ObjectResult<S_HedefSatisDurumu_Result> S_HedefSatisDurumu(Nullable<int> bayiID, Nullable<System.DateTime> baslangicTarihi, Nullable<System.DateTime> bitisTarihi)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("BaslangicTarihi", baslangicTarihi) :
                new ObjectParameter("BaslangicTarihi", typeof(System.DateTime));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("BitisTarihi", bitisTarihi) :
                new ObjectParameter("BitisTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_HedefSatisDurumu_Result>("S_HedefSatisDurumu", bayiIDParameter, baslangicTarihiParameter, bitisTarihiParameter);
        }
    
        public virtual ObjectResult<S_HedefSatisDurumuPivot_Result> S_HedefSatisDurumuPivot(Nullable<int> bayiID, Nullable<System.DateTime> baslangicTarihi, Nullable<System.DateTime> bitisTarihi)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("BaslangicTarihi", baslangicTarihi) :
                new ObjectParameter("BaslangicTarihi", typeof(System.DateTime));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("BitisTarihi", bitisTarihi) :
                new ObjectParameter("BitisTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_HedefSatisDurumuPivot_Result>("S_HedefSatisDurumuPivot", bayiIDParameter, baslangicTarihiParameter, bitisTarihiParameter);
        }
    
        public virtual ObjectResult<S_MenuNavigation_Result> S_MenuNavigation(Nullable<System.Guid> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_MenuNavigation_Result>("S_MenuNavigation", userIDParameter);
        }
    
        public virtual ObjectResult<I_SilverRapor_Excel_Result> I_SilverRapor_Excel(string excelDosyaYolu, Nullable<System.Guid> userKey)
        {
            var excelDosyaYoluParameter = excelDosyaYolu != null ?
                new ObjectParameter("ExcelDosyaYolu", excelDosyaYolu) :
                new ObjectParameter("ExcelDosyaYolu", typeof(string));
    
            var userKeyParameter = userKey.HasValue ?
                new ObjectParameter("UserKey", userKey) :
                new ObjectParameter("UserKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_SilverRapor_Excel_Result>("I_SilverRapor_Excel", excelDosyaYoluParameter, userKeyParameter);
        }
    
        public virtual ObjectResult<S_Bayi_Result> S_Bayi(Nullable<int> bayiID)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Bayi_Result>("S_Bayi", bayiIDParameter);
        }
    
        public virtual ObjectResult<S_BayiID_Result> S_BayiID(string bayiKodu)
        {
            var bayiKoduParameter = bayiKodu != null ?
                new ObjectParameter("BayiKodu", bayiKodu) :
                new ObjectParameter("BayiKodu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_BayiID_Result>("S_BayiID", bayiKoduParameter);
        }
    
        public virtual ObjectResult<OD_SP_006_01_CARI_EKSTRE_Result> OD_SP_006_01_CARI_EKSTRE(string cARI_KODU)
        {
            var cARI_KODUParameter = cARI_KODU != null ?
                new ObjectParameter("CARI_KODU", cARI_KODU) :
                new ObjectParameter("CARI_KODU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_006_01_CARI_EKSTRE_Result>("OD_SP_006_01_CARI_EKSTRE", cARI_KODUParameter);
        }
    
        public virtual ObjectResult<OD_SP_AE_KAR_Result> OD_SP_AE_KAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_AE_KAR_Result>("OD_SP_AE_KAR");
        }
    
        public virtual ObjectResult<OD_SP_AEO_ENVANTER_006_Result> OD_SP_AEO_ENVANTER_006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_AEO_ENVANTER_006_Result>("OD_SP_AEO_ENVANTER_006");
        }
    
        public virtual ObjectResult<OD_SP_PRONIST_006_FATURA_Result> OD_SP_PRONIST_006_FATURA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_PRONIST_006_FATURA_Result>("OD_SP_PRONIST_006_FATURA");
        }
    
        public virtual ObjectResult<OD_SP_US_006_01_MALZEME_SONALIMMALIYET_Result> OD_SP_US_006_01_MALZEME_SONALIMMALIYET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_US_006_01_MALZEME_SONALIMMALIYET_Result>("OD_SP_US_006_01_MALZEME_SONALIMMALIYET");
        }
    
        public virtual ObjectResult<S_AktivasyonAraRaporu_Result> S_AktivasyonAraRaporu(Nullable<int> bayiID)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivasyonAraRaporu_Result>("S_AktivasyonAraRaporu", bayiIDParameter);
        }
    
        public virtual ObjectResult<I_AktivasyonAraRapor_Excel_Result> I_AktivasyonAraRapor_Excel(string excelDosyaYolu, Nullable<System.Guid> userKey)
        {
            var excelDosyaYoluParameter = excelDosyaYolu != null ?
                new ObjectParameter("ExcelDosyaYolu", excelDosyaYolu) :
                new ObjectParameter("ExcelDosyaYolu", typeof(string));
    
            var userKeyParameter = userKey.HasValue ?
                new ObjectParameter("UserKey", userKey) :
                new ObjectParameter("UserKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_AktivasyonAraRapor_Excel_Result>("I_AktivasyonAraRapor_Excel", excelDosyaYoluParameter, userKeyParameter);
        }
    
        public virtual ObjectResult<S_Urunler_Result> S_Urunler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Urunler_Result>("S_Urunler");
        }
    
        public virtual int D_Duyurular(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_Duyurular", iDParameter);
        }
    
        public virtual int I_Duyurular(string baslik, string aciklama, Nullable<System.DateTime> duyuruTarihi)
        {
            var baslikParameter = baslik != null ?
                new ObjectParameter("Baslik", baslik) :
                new ObjectParameter("Baslik", typeof(string));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var duyuruTarihiParameter = duyuruTarihi.HasValue ?
                new ObjectParameter("DuyuruTarihi", duyuruTarihi) :
                new ObjectParameter("DuyuruTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_Duyurular", baslikParameter, aciklamaParameter, duyuruTarihiParameter);
        }
    
        public virtual int U_Duyurular(Nullable<int> iD, string baslik, string aciklama, Nullable<System.DateTime> duyuruTarihi)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var baslikParameter = baslik != null ?
                new ObjectParameter("Baslik", baslik) :
                new ObjectParameter("Baslik", typeof(string));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var duyuruTarihiParameter = duyuruTarihi.HasValue ?
                new ObjectParameter("DuyuruTarihi", duyuruTarihi) :
                new ObjectParameter("DuyuruTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_Duyurular", iDParameter, baslikParameter, aciklamaParameter, duyuruTarihiParameter);
        }
    
        public virtual int D_DuyurularSlider(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_DuyurularSlider", iDParameter);
        }
    
        public virtual int I_DuyurularSlider(string resimAdi, Nullable<int> siraNo, Nullable<bool> aktif, string slideAdi)
        {
            var resimAdiParameter = resimAdi != null ?
                new ObjectParameter("ResimAdi", resimAdi) :
                new ObjectParameter("ResimAdi", typeof(string));
    
            var siraNoParameter = siraNo.HasValue ?
                new ObjectParameter("SiraNo", siraNo) :
                new ObjectParameter("SiraNo", typeof(int));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var slideAdiParameter = slideAdi != null ?
                new ObjectParameter("SlideAdi", slideAdi) :
                new ObjectParameter("SlideAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_DuyurularSlider", resimAdiParameter, siraNoParameter, aktifParameter, slideAdiParameter);
        }
    
        public virtual ObjectResult<S_DuyurularSlider_Result> S_DuyurularSlider(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DuyurularSlider_Result>("S_DuyurularSlider", iDParameter);
        }
    
        public virtual int U_DuyurularSlider(Nullable<int> iD, string resimAdi, Nullable<int> siraNo, Nullable<bool> aktif, string slideAdi)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var resimAdiParameter = resimAdi != null ?
                new ObjectParameter("ResimAdi", resimAdi) :
                new ObjectParameter("ResimAdi", typeof(string));
    
            var siraNoParameter = siraNo.HasValue ?
                new ObjectParameter("SiraNo", siraNo) :
                new ObjectParameter("SiraNo", typeof(int));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var slideAdiParameter = slideAdi != null ?
                new ObjectParameter("SlideAdi", slideAdi) :
                new ObjectParameter("SlideAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_DuyurularSlider", iDParameter, resimAdiParameter, siraNoParameter, aktifParameter, slideAdiParameter);
        }
    
        public virtual ObjectResult<I_TemlikRapor_Excel_Result> I_TemlikRapor_Excel(string excelDosyaYolu, Nullable<System.Guid> userKey)
        {
            var excelDosyaYoluParameter = excelDosyaYolu != null ?
                new ObjectParameter("ExcelDosyaYolu", excelDosyaYolu) :
                new ObjectParameter("ExcelDosyaYolu", typeof(string));
    
            var userKeyParameter = userKey.HasValue ?
                new ObjectParameter("UserKey", userKey) :
                new ObjectParameter("UserKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_TemlikRapor_Excel_Result>("I_TemlikRapor_Excel", excelDosyaYoluParameter, userKeyParameter);
        }
    
        public virtual ObjectResult<S_CihazTemlikRaporu_Result> S_CihazTemlikRaporu(Nullable<int> bayiID)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CihazTemlikRaporu_Result>("S_CihazTemlikRaporu", bayiIDParameter);
        }
    
        public virtual ObjectResult<I_PrimHakedis_Excel_Result> I_PrimHakedis_Excel(string excelDosyaYolu, Nullable<System.Guid> userKey)
        {
            var excelDosyaYoluParameter = excelDosyaYolu != null ?
                new ObjectParameter("ExcelDosyaYolu", excelDosyaYolu) :
                new ObjectParameter("ExcelDosyaYolu", typeof(string));
    
            var userKeyParameter = userKey.HasValue ?
                new ObjectParameter("UserKey", userKey) :
                new ObjectParameter("UserKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_PrimHakedis_Excel_Result>("I_PrimHakedis_Excel", excelDosyaYoluParameter, userKeyParameter);
        }
    
        public virtual ObjectResult<S_PrimHakedisRaporu_Result> S_PrimHakedisRaporu(Nullable<int> bayiID)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_PrimHakedisRaporu_Result>("S_PrimHakedisRaporu", bayiIDParameter);
        }
    
        public virtual ObjectResult<I_AlSatKarlilik_Excel_Result> I_AlSatKarlilik_Excel(string excelDosyaYolu, Nullable<System.Guid> userKey)
        {
            var excelDosyaYoluParameter = excelDosyaYolu != null ?
                new ObjectParameter("ExcelDosyaYolu", excelDosyaYolu) :
                new ObjectParameter("ExcelDosyaYolu", typeof(string));
    
            var userKeyParameter = userKey.HasValue ?
                new ObjectParameter("UserKey", userKey) :
                new ObjectParameter("UserKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_AlSatKarlilik_Excel_Result>("I_AlSatKarlilik_Excel", excelDosyaYoluParameter, userKeyParameter);
        }
    
        public virtual ObjectResult<S_AlSatKarlilik_Result> S_AlSatKarlilik(Nullable<int> bayiID)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AlSatKarlilik_Result>("S_AlSatKarlilik", bayiIDParameter);
        }
    
        public virtual ObjectResult<R_AktivasyonAraRaporu_Result> R_AktivasyonAraRaporu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_AktivasyonAraRaporu_Result>("R_AktivasyonAraRaporu");
        }
    
        public virtual ObjectResult<S_Tip_Result> S_Tip(Nullable<int> ayiracID)
        {
            var ayiracIDParameter = ayiracID.HasValue ?
                new ObjectParameter("AyiracID", ayiracID) :
                new ObjectParameter("AyiracID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Tip_Result>("S_Tip", ayiracIDParameter);
        }
    
        public virtual ObjectResult<S_AdresIlce_Result> S_AdresIlce(Nullable<int> sehirID)
        {
            var sehirIDParameter = sehirID.HasValue ?
                new ObjectParameter("SehirID", sehirID) :
                new ObjectParameter("SehirID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AdresIlce_Result>("S_AdresIlce", sehirIDParameter);
        }
    
        public virtual ObjectResult<S_AdresSehir_Result> S_AdresSehir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AdresSehir_Result>("S_AdresSehir");
        }
    
        public virtual ObjectResult<S_MusteriTemsilcisi_Result> S_MusteriTemsilcisi(Nullable<System.Guid> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_MusteriTemsilcisi_Result>("S_MusteriTemsilcisi", userIDParameter);
        }
    
        public virtual ObjectResult<I_Bayi_Result> I_Bayi(Nullable<bool> aktif, string bayiKodu, string bayiAdi, string bayiCariAdi, Nullable<int> grup_TipID1, Nullable<int> bolge_TipID2, Nullable<int> sehirID, Nullable<int> ilceID, Nullable<int> semtID, Nullable<int> mahalleID, Nullable<int> pKID, string adres, string telefon, string faks, string cep, string mail, string yetkiliAdiSoyadi, Nullable<int> musteriTemsilcisiID, Nullable<int> bayiTipi_TipID3, string resimAdi)
        {
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var bayiKoduParameter = bayiKodu != null ?
                new ObjectParameter("BayiKodu", bayiKodu) :
                new ObjectParameter("BayiKodu", typeof(string));
    
            var bayiAdiParameter = bayiAdi != null ?
                new ObjectParameter("BayiAdi", bayiAdi) :
                new ObjectParameter("BayiAdi", typeof(string));
    
            var bayiCariAdiParameter = bayiCariAdi != null ?
                new ObjectParameter("BayiCariAdi", bayiCariAdi) :
                new ObjectParameter("BayiCariAdi", typeof(string));
    
            var grup_TipID1Parameter = grup_TipID1.HasValue ?
                new ObjectParameter("Grup_TipID1", grup_TipID1) :
                new ObjectParameter("Grup_TipID1", typeof(int));
    
            var bolge_TipID2Parameter = bolge_TipID2.HasValue ?
                new ObjectParameter("Bolge_TipID2", bolge_TipID2) :
                new ObjectParameter("Bolge_TipID2", typeof(int));
    
            var sehirIDParameter = sehirID.HasValue ?
                new ObjectParameter("SehirID", sehirID) :
                new ObjectParameter("SehirID", typeof(int));
    
            var ilceIDParameter = ilceID.HasValue ?
                new ObjectParameter("IlceID", ilceID) :
                new ObjectParameter("IlceID", typeof(int));
    
            var semtIDParameter = semtID.HasValue ?
                new ObjectParameter("SemtID", semtID) :
                new ObjectParameter("SemtID", typeof(int));
    
            var mahalleIDParameter = mahalleID.HasValue ?
                new ObjectParameter("MahalleID", mahalleID) :
                new ObjectParameter("MahalleID", typeof(int));
    
            var pKIDParameter = pKID.HasValue ?
                new ObjectParameter("PKID", pKID) :
                new ObjectParameter("PKID", typeof(int));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var faksParameter = faks != null ?
                new ObjectParameter("Faks", faks) :
                new ObjectParameter("Faks", typeof(string));
    
            var cepParameter = cep != null ?
                new ObjectParameter("Cep", cep) :
                new ObjectParameter("Cep", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var yetkiliAdiSoyadiParameter = yetkiliAdiSoyadi != null ?
                new ObjectParameter("YetkiliAdiSoyadi", yetkiliAdiSoyadi) :
                new ObjectParameter("YetkiliAdiSoyadi", typeof(string));
    
            var musteriTemsilcisiIDParameter = musteriTemsilcisiID.HasValue ?
                new ObjectParameter("MusteriTemsilcisiID", musteriTemsilcisiID) :
                new ObjectParameter("MusteriTemsilcisiID", typeof(int));
    
            var bayiTipi_TipID3Parameter = bayiTipi_TipID3.HasValue ?
                new ObjectParameter("BayiTipi_TipID3", bayiTipi_TipID3) :
                new ObjectParameter("BayiTipi_TipID3", typeof(int));
    
            var resimAdiParameter = resimAdi != null ?
                new ObjectParameter("ResimAdi", resimAdi) :
                new ObjectParameter("ResimAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_Bayi_Result>("I_Bayi", aktifParameter, bayiKoduParameter, bayiAdiParameter, bayiCariAdiParameter, grup_TipID1Parameter, bolge_TipID2Parameter, sehirIDParameter, ilceIDParameter, semtIDParameter, mahalleIDParameter, pKIDParameter, adresParameter, telefonParameter, faksParameter, cepParameter, mailParameter, yetkiliAdiSoyadiParameter, musteriTemsilcisiIDParameter, bayiTipi_TipID3Parameter, resimAdiParameter);
        }
    
        public virtual int U_Bayi(Nullable<int> kayitID, Nullable<bool> aktif, string bayiKodu, string bayiAdi, string bayiCariAdi, Nullable<int> grup_TipID1, Nullable<int> bolge_TipID2, Nullable<int> sehirID, Nullable<int> ilceID, Nullable<int> semtID, Nullable<int> mahalleID, Nullable<int> pKID, string adres, string telefon, string faks, string cep, string mail, string yetkiliAdiSoyadi, Nullable<int> musteriTemsilcisiID, Nullable<int> bayiTipi_TipID3, string resimAdi)
        {
            var kayitIDParameter = kayitID.HasValue ?
                new ObjectParameter("KayitID", kayitID) :
                new ObjectParameter("KayitID", typeof(int));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var bayiKoduParameter = bayiKodu != null ?
                new ObjectParameter("BayiKodu", bayiKodu) :
                new ObjectParameter("BayiKodu", typeof(string));
    
            var bayiAdiParameter = bayiAdi != null ?
                new ObjectParameter("BayiAdi", bayiAdi) :
                new ObjectParameter("BayiAdi", typeof(string));
    
            var bayiCariAdiParameter = bayiCariAdi != null ?
                new ObjectParameter("BayiCariAdi", bayiCariAdi) :
                new ObjectParameter("BayiCariAdi", typeof(string));
    
            var grup_TipID1Parameter = grup_TipID1.HasValue ?
                new ObjectParameter("Grup_TipID1", grup_TipID1) :
                new ObjectParameter("Grup_TipID1", typeof(int));
    
            var bolge_TipID2Parameter = bolge_TipID2.HasValue ?
                new ObjectParameter("Bolge_TipID2", bolge_TipID2) :
                new ObjectParameter("Bolge_TipID2", typeof(int));
    
            var sehirIDParameter = sehirID.HasValue ?
                new ObjectParameter("SehirID", sehirID) :
                new ObjectParameter("SehirID", typeof(int));
    
            var ilceIDParameter = ilceID.HasValue ?
                new ObjectParameter("IlceID", ilceID) :
                new ObjectParameter("IlceID", typeof(int));
    
            var semtIDParameter = semtID.HasValue ?
                new ObjectParameter("SemtID", semtID) :
                new ObjectParameter("SemtID", typeof(int));
    
            var mahalleIDParameter = mahalleID.HasValue ?
                new ObjectParameter("MahalleID", mahalleID) :
                new ObjectParameter("MahalleID", typeof(int));
    
            var pKIDParameter = pKID.HasValue ?
                new ObjectParameter("PKID", pKID) :
                new ObjectParameter("PKID", typeof(int));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var faksParameter = faks != null ?
                new ObjectParameter("Faks", faks) :
                new ObjectParameter("Faks", typeof(string));
    
            var cepParameter = cep != null ?
                new ObjectParameter("Cep", cep) :
                new ObjectParameter("Cep", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var yetkiliAdiSoyadiParameter = yetkiliAdiSoyadi != null ?
                new ObjectParameter("YetkiliAdiSoyadi", yetkiliAdiSoyadi) :
                new ObjectParameter("YetkiliAdiSoyadi", typeof(string));
    
            var musteriTemsilcisiIDParameter = musteriTemsilcisiID.HasValue ?
                new ObjectParameter("MusteriTemsilcisiID", musteriTemsilcisiID) :
                new ObjectParameter("MusteriTemsilcisiID", typeof(int));
    
            var bayiTipi_TipID3Parameter = bayiTipi_TipID3.HasValue ?
                new ObjectParameter("BayiTipi_TipID3", bayiTipi_TipID3) :
                new ObjectParameter("BayiTipi_TipID3", typeof(int));
    
            var resimAdiParameter = resimAdi != null ?
                new ObjectParameter("ResimAdi", resimAdi) :
                new ObjectParameter("ResimAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_Bayi", kayitIDParameter, aktifParameter, bayiKoduParameter, bayiAdiParameter, bayiCariAdiParameter, grup_TipID1Parameter, bolge_TipID2Parameter, sehirIDParameter, ilceIDParameter, semtIDParameter, mahalleIDParameter, pKIDParameter, adresParameter, telefonParameter, faksParameter, cepParameter, mailParameter, yetkiliAdiSoyadiParameter, musteriTemsilcisiIDParameter, bayiTipi_TipID3Parameter, resimAdiParameter);
        }
    
        public virtual int I_DuyurularPopup(string resimAdi, string duyuruAdi)
        {
            var resimAdiParameter = resimAdi != null ?
                new ObjectParameter("ResimAdi", resimAdi) :
                new ObjectParameter("ResimAdi", typeof(string));
    
            var duyuruAdiParameter = duyuruAdi != null ?
                new ObjectParameter("DuyuruAdi", duyuruAdi) :
                new ObjectParameter("DuyuruAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_DuyurularPopup", resimAdiParameter, duyuruAdiParameter);
        }
    
        public virtual ObjectResult<S_DuyurularPopup_Result> S_DuyurularPopup(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DuyurularPopup_Result>("S_DuyurularPopup", userIdParameter);
        }
    
        public virtual int I_DuyurularPopupLog(Nullable<System.Guid> userId, string resimAdi)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var resimAdiParameter = resimAdi != null ?
                new ObjectParameter("ResimAdi", resimAdi) :
                new ObjectParameter("ResimAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_DuyurularPopupLog", userIdParameter, resimAdiParameter);
        }
    
        public virtual ObjectResult<S_BayiTeminat_Result> S_BayiTeminat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_BayiTeminat_Result>("S_BayiTeminat");
        }
    
        public virtual ObjectResult<I_CariTakipTeminat_Excel_Result> I_CariTakipTeminat_Excel(string excelDosyaYolu, Nullable<System.Guid> userKey)
        {
            var excelDosyaYoluParameter = excelDosyaYolu != null ?
                new ObjectParameter("ExcelDosyaYolu", excelDosyaYolu) :
                new ObjectParameter("ExcelDosyaYolu", typeof(string));
    
            var userKeyParameter = userKey.HasValue ?
                new ObjectParameter("UserKey", userKey) :
                new ObjectParameter("UserKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_CariTakipTeminat_Excel_Result>("I_CariTakipTeminat_Excel", excelDosyaYoluParameter, userKeyParameter);
        }
    
        public virtual ObjectResult<S_CihazTakipAraRapor_Result> S_CihazTakipAraRapor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CihazTakipAraRapor_Result>("S_CihazTakipAraRapor");
        }
    
        public virtual ObjectResult<S_Dokumanlar_Result> S_Dokumanlar(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Dokumanlar_Result>("S_Dokumanlar", iDParameter);
        }
    
        public virtual int I_Dokuman(string dokumanAdi, string dosyaAdi, Nullable<bool> aktif, Nullable<int> dokumanTipi_TipID5)
        {
            var dokumanAdiParameter = dokumanAdi != null ?
                new ObjectParameter("DokumanAdi", dokumanAdi) :
                new ObjectParameter("DokumanAdi", typeof(string));
    
            var dosyaAdiParameter = dosyaAdi != null ?
                new ObjectParameter("DosyaAdi", dosyaAdi) :
                new ObjectParameter("DosyaAdi", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var dokumanTipi_TipID5Parameter = dokumanTipi_TipID5.HasValue ?
                new ObjectParameter("DokumanTipi_TipID5", dokumanTipi_TipID5) :
                new ObjectParameter("DokumanTipi_TipID5", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_Dokuman", dokumanAdiParameter, dosyaAdiParameter, aktifParameter, dokumanTipi_TipID5Parameter);
        }
    
        public virtual int D_Dokumanlar(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_Dokumanlar", iDParameter);
        }
    
        public virtual int I_Siparislerim(Nullable<int> bayiID, Nullable<int> urunID, Nullable<int> adet)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            var urunIDParameter = urunID.HasValue ?
                new ObjectParameter("UrunID", urunID) :
                new ObjectParameter("UrunID", typeof(int));
    
            var adetParameter = adet.HasValue ?
                new ObjectParameter("Adet", adet) :
                new ObjectParameter("Adet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_Siparislerim", bayiIDParameter, urunIDParameter, adetParameter);
        }
    
        public virtual ObjectResult<S_Siparislerim_Result> S_Siparislerim(Nullable<int> bayiID)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Siparislerim_Result>("S_Siparislerim", bayiIDParameter);
        }
    
        public virtual ObjectResult<S_Siparisler_Result> S_Siparisler(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Siparisler_Result>("S_Siparisler", iDParameter);
        }
    
        public virtual int D_Siparis(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_Siparis", iDParameter);
        }
    
        public virtual int U_Siparis(Nullable<int> iD, Nullable<int> onayID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var onayIDParameter = onayID.HasValue ?
                new ObjectParameter("OnayID", onayID) :
                new ObjectParameter("OnayID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_Siparis", iDParameter, onayIDParameter);
        }
    
        public virtual int D_UrunTanimlari(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_UrunTanimlari", iDParameter);
        }
    
        public virtual int I_UrunTanimlari(string urunKodu, string urunAdi, Nullable<int> kategoriID_TipID4, string marka, string model, Nullable<decimal> fiyat, string resim)
        {
            var urunKoduParameter = urunKodu != null ?
                new ObjectParameter("UrunKodu", urunKodu) :
                new ObjectParameter("UrunKodu", typeof(string));
    
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            var kategoriID_TipID4Parameter = kategoriID_TipID4.HasValue ?
                new ObjectParameter("KategoriID_TipID4", kategoriID_TipID4) :
                new ObjectParameter("KategoriID_TipID4", typeof(int));
    
            var markaParameter = marka != null ?
                new ObjectParameter("Marka", marka) :
                new ObjectParameter("Marka", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(string));
    
            var fiyatParameter = fiyat.HasValue ?
                new ObjectParameter("Fiyat", fiyat) :
                new ObjectParameter("Fiyat", typeof(decimal));
    
            var resimParameter = resim != null ?
                new ObjectParameter("Resim", resim) :
                new ObjectParameter("Resim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_UrunTanimlari", urunKoduParameter, urunAdiParameter, kategoriID_TipID4Parameter, markaParameter, modelParameter, fiyatParameter, resimParameter);
        }
    
        public virtual int U_UrunTanimlari(Nullable<int> iD, string urunKodu, string urunAdi, Nullable<int> kategoriID_TipID4, string marka, string model, Nullable<decimal> fiyat, string resim)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var urunKoduParameter = urunKodu != null ?
                new ObjectParameter("UrunKodu", urunKodu) :
                new ObjectParameter("UrunKodu", typeof(string));
    
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            var kategoriID_TipID4Parameter = kategoriID_TipID4.HasValue ?
                new ObjectParameter("KategoriID_TipID4", kategoriID_TipID4) :
                new ObjectParameter("KategoriID_TipID4", typeof(int));
    
            var markaParameter = marka != null ?
                new ObjectParameter("Marka", marka) :
                new ObjectParameter("Marka", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(string));
    
            var fiyatParameter = fiyat.HasValue ?
                new ObjectParameter("Fiyat", fiyat) :
                new ObjectParameter("Fiyat", typeof(decimal));
    
            var resimParameter = resim != null ?
                new ObjectParameter("Resim", resim) :
                new ObjectParameter("Resim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_UrunTanimlari", iDParameter, urunKoduParameter, urunAdiParameter, kategoriID_TipID4Parameter, markaParameter, modelParameter, fiyatParameter, resimParameter);
        }
    
        public virtual ObjectResult<S_MenuYetkileri_Result> S_MenuYetkileri(Nullable<int> sP_IslemTipi, Nullable<System.Guid> roleID)
        {
            var sP_IslemTipiParameter = sP_IslemTipi.HasValue ?
                new ObjectParameter("SP_IslemTipi", sP_IslemTipi) :
                new ObjectParameter("SP_IslemTipi", typeof(int));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_MenuYetkileri_Result>("S_MenuYetkileri", sP_IslemTipiParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<I_Aktivasyon_Result> I_Aktivasyon(Nullable<int> bayiID, Nullable<System.Guid> userId, string adi, string soyadi, Nullable<decimal> tCKN, string anneKizlikSoyadi, string adres, Nullable<int> sehirID, Nullable<int> ilceID, Nullable<int> postaKodu, string eMailAdresi, string iletisimTelefonu, string hatTelNumarasi, string simkartSeriNo, Nullable<int> hatTarifeID, string aciklama, Nullable<bool> mnp, Nullable<int> simkartTipi_TipID9, Nullable<int> eFatura_TipID12)
        {
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var soyadiParameter = soyadi != null ?
                new ObjectParameter("Soyadi", soyadi) :
                new ObjectParameter("Soyadi", typeof(string));
    
            var tCKNParameter = tCKN.HasValue ?
                new ObjectParameter("TCKN", tCKN) :
                new ObjectParameter("TCKN", typeof(decimal));
    
            var anneKizlikSoyadiParameter = anneKizlikSoyadi != null ?
                new ObjectParameter("AnneKizlikSoyadi", anneKizlikSoyadi) :
                new ObjectParameter("AnneKizlikSoyadi", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var sehirIDParameter = sehirID.HasValue ?
                new ObjectParameter("SehirID", sehirID) :
                new ObjectParameter("SehirID", typeof(int));
    
            var ilceIDParameter = ilceID.HasValue ?
                new ObjectParameter("IlceID", ilceID) :
                new ObjectParameter("IlceID", typeof(int));
    
            var postaKoduParameter = postaKodu.HasValue ?
                new ObjectParameter("PostaKodu", postaKodu) :
                new ObjectParameter("PostaKodu", typeof(int));
    
            var eMailAdresiParameter = eMailAdresi != null ?
                new ObjectParameter("EMailAdresi", eMailAdresi) :
                new ObjectParameter("EMailAdresi", typeof(string));
    
            var iletisimTelefonuParameter = iletisimTelefonu != null ?
                new ObjectParameter("IletisimTelefonu", iletisimTelefonu) :
                new ObjectParameter("IletisimTelefonu", typeof(string));
    
            var hatTelNumarasiParameter = hatTelNumarasi != null ?
                new ObjectParameter("HatTelNumarasi", hatTelNumarasi) :
                new ObjectParameter("HatTelNumarasi", typeof(string));
    
            var simkartSeriNoParameter = simkartSeriNo != null ?
                new ObjectParameter("SimkartSeriNo", simkartSeriNo) :
                new ObjectParameter("SimkartSeriNo", typeof(string));
    
            var hatTarifeIDParameter = hatTarifeID.HasValue ?
                new ObjectParameter("HatTarifeID", hatTarifeID) :
                new ObjectParameter("HatTarifeID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var mnpParameter = mnp.HasValue ?
                new ObjectParameter("Mnp", mnp) :
                new ObjectParameter("Mnp", typeof(bool));
    
            var simkartTipi_TipID9Parameter = simkartTipi_TipID9.HasValue ?
                new ObjectParameter("SimkartTipi_TipID9", simkartTipi_TipID9) :
                new ObjectParameter("SimkartTipi_TipID9", typeof(int));
    
            var eFatura_TipID12Parameter = eFatura_TipID12.HasValue ?
                new ObjectParameter("EFatura_TipID12", eFatura_TipID12) :
                new ObjectParameter("EFatura_TipID12", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_Aktivasyon_Result>("I_Aktivasyon", bayiIDParameter, userIdParameter, adiParameter, soyadiParameter, tCKNParameter, anneKizlikSoyadiParameter, adresParameter, sehirIDParameter, ilceIDParameter, postaKoduParameter, eMailAdresiParameter, iletisimTelefonuParameter, hatTelNumarasiParameter, simkartSeriNoParameter, hatTarifeIDParameter, aciklamaParameter, mnpParameter, simkartTipi_TipID9Parameter, eFatura_TipID12Parameter);
        }
    
        public virtual ObjectResult<S_Tarife_Result> S_Tarife(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Tarife_Result>("S_Tarife", iDParameter);
        }
    
        public virtual ObjectResult<S_Aktivasyon_Result> S_Aktivasyon(Nullable<int> iD, Nullable<int> bayiID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Aktivasyon_Result>("S_Aktivasyon", iDParameter, bayiIDParameter);
        }
    
        public virtual ObjectResult<S_Roles_Result> S_Roles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Roles_Result>("S_Roles");
        }
    
        public virtual int I_MenuYetkileri(Nullable<int> menuID, Nullable<System.Guid> roleID)
        {
            var menuIDParameter = menuID.HasValue ?
                new ObjectParameter("MenuID", menuID) :
                new ObjectParameter("MenuID", typeof(int));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_MenuYetkileri", menuIDParameter, roleIDParameter);
        }
    
        public virtual int D_RoleMenuYetkileriSil(Nullable<System.Guid> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_RoleMenuYetkileriSil", roleIdParameter);
        }
    
        public virtual int I_AktivasyonEvrak(string dosyaAdi, Nullable<int> dosyaTipi, Nullable<int> evrakTipi, Nullable<int> aktivasyonID)
        {
            var dosyaAdiParameter = dosyaAdi != null ?
                new ObjectParameter("DosyaAdi", dosyaAdi) :
                new ObjectParameter("DosyaAdi", typeof(string));
    
            var dosyaTipiParameter = dosyaTipi.HasValue ?
                new ObjectParameter("DosyaTipi", dosyaTipi) :
                new ObjectParameter("DosyaTipi", typeof(int));
    
            var evrakTipiParameter = evrakTipi.HasValue ?
                new ObjectParameter("EvrakTipi", evrakTipi) :
                new ObjectParameter("EvrakTipi", typeof(int));
    
            var aktivasyonIDParameter = aktivasyonID.HasValue ?
                new ObjectParameter("AktivasyonID", aktivasyonID) :
                new ObjectParameter("AktivasyonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_AktivasyonEvrak", dosyaAdiParameter, dosyaTipiParameter, evrakTipiParameter, aktivasyonIDParameter);
        }
    
        public virtual ObjectResult<S_AktivasyonFaturasiz_Result> S_AktivasyonFaturasiz(Nullable<int> iD, Nullable<int> bayiID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivasyonFaturasiz_Result>("S_AktivasyonFaturasiz", iDParameter, bayiIDParameter);
        }
    
        public virtual ObjectResult<S_AktivasyonSebekeIciGecis_Result> S_AktivasyonSebekeIciGecis(Nullable<int> iD, Nullable<int> bayiID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivasyonSebekeIciGecis_Result>("S_AktivasyonSebekeIciGecis", iDParameter, bayiIDParameter);
        }
    
        public virtual ObjectResult<S_AktivasyonTaahhutname_Result> S_AktivasyonTaahhutname(Nullable<int> iD, Nullable<int> bayiID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivasyonTaahhutname_Result>("S_AktivasyonTaahhutname", iDParameter, bayiIDParameter);
        }
    
        public virtual ObjectResult<S_AktivasyonHatIptal_Result> S_AktivasyonHatIptal(Nullable<int> iD, Nullable<int> bayiID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivasyonHatIptal_Result>("S_AktivasyonHatIptal", iDParameter, bayiIDParameter);
        }
    
        public virtual ObjectResult<S_AktivasyonVodafoneNet_Result> S_AktivasyonVodafoneNet(Nullable<int> iD, Nullable<int> bayiID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivasyonVodafoneNet_Result>("S_AktivasyonVodafoneNet", iDParameter, bayiIDParameter);
        }
    
        public virtual ObjectResult<S_AktivasyonEFatura_Result> S_AktivasyonEFatura(Nullable<int> iD, Nullable<int> bayiID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var bayiIDParameter = bayiID.HasValue ?
                new ObjectParameter("BayiID", bayiID) :
                new ObjectParameter("BayiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivasyonEFatura_Result>("S_AktivasyonEFatura", iDParameter, bayiIDParameter);
        }
    
        public virtual ObjectResult<S_AktivasyonYonetici_Result> S_AktivasyonYonetici(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivasyonYonetici_Result>("S_AktivasyonYonetici", iDParameter);
        }
    
        public virtual int D_MusteriTemsilcisi(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_MusteriTemsilcisi", iDParameter);
        }
    
        public virtual int I_MusteriTemsilcisi(string adiSoyadi, Nullable<System.Guid> userId)
        {
            var adiSoyadiParameter = adiSoyadi != null ?
                new ObjectParameter("AdiSoyadi", adiSoyadi) :
                new ObjectParameter("AdiSoyadi", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_MusteriTemsilcisi", adiSoyadiParameter, userIdParameter);
        }
    
        public virtual int U_MusteriTemsilcisi(Nullable<int> iD, string adiSoyadi, Nullable<System.Guid> userId)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var adiSoyadiParameter = adiSoyadi != null ?
                new ObjectParameter("AdiSoyadi", adiSoyadi) :
                new ObjectParameter("AdiSoyadi", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_MusteriTemsilcisi", iDParameter, adiSoyadiParameter, userIdParameter);
        }
    
        public virtual ObjectResult<S_Kullanici_Result> S_Kullanici()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Kullanici_Result>("S_Kullanici");
        }
    
        public virtual int D_Bolge(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_Bolge", iDParameter);
        }
    
        public virtual int I_Bolge(string adi)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_Bolge", adiParameter);
        }
    
        public virtual ObjectResult<S_Bolge_Result> S_Bolge()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Bolge_Result>("S_Bolge");
        }
    
        public virtual int U_Bolge(Nullable<int> iD, string adi)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_Bolge", iDParameter, adiParameter);
        }
    
        public virtual int D_Grup(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_Grup", iDParameter);
        }
    
        public virtual int I_Grup(string adi)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_Grup", adiParameter);
        }
    
        public virtual ObjectResult<S_Grup_Result> S_Grup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Grup_Result>("S_Grup");
        }
    
        public virtual int U_Grup(Nullable<int> iD, string adi)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_Grup", iDParameter, adiParameter);
        }
    
        public virtual int D_TemlikRapor_Excel(Nullable<int> ay, Nullable<int> yil, string excelDosyaYolu, Nullable<System.Guid> userKey)
        {
            var ayParameter = ay.HasValue ?
                new ObjectParameter("Ay", ay) :
                new ObjectParameter("Ay", typeof(int));
    
            var yilParameter = yil.HasValue ?
                new ObjectParameter("Yil", yil) :
                new ObjectParameter("Yil", typeof(int));
    
            var excelDosyaYoluParameter = excelDosyaYolu != null ?
                new ObjectParameter("ExcelDosyaYolu", excelDosyaYolu) :
                new ObjectParameter("ExcelDosyaYolu", typeof(string));
    
            var userKeyParameter = userKey.HasValue ?
                new ObjectParameter("UserKey", userKey) :
                new ObjectParameter("UserKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_TemlikRapor_Excel", ayParameter, yilParameter, excelDosyaYoluParameter, userKeyParameter);
        }
    }
}
