//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMProjectWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TIGER2Entities : DbContext
    {
        public TIGER2Entities()
            : base("name=TIGER2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<OD_SP_006_01_CARI_EKSTRE_Result> OD_SP_006_01_CARI_EKSTRE(string cARI_KODU)
        {
            var cARI_KODUParameter = cARI_KODU != null ?
                new ObjectParameter("CARI_KODU", cARI_KODU) :
                new ObjectParameter("CARI_KODU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_006_01_CARI_EKSTRE_Result>("OD_SP_006_01_CARI_EKSTRE", cARI_KODUParameter);
        }
    
        public virtual ObjectResult<OD_SP_BayiBakiye_Result> OD_SP_BayiBakiye(string bayiKodu)
        {
            var bayiKoduParameter = bayiKodu != null ?
                new ObjectParameter("BayiKodu", bayiKodu) :
                new ObjectParameter("BayiKodu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_BayiBakiye_Result>("OD_SP_BayiBakiye", bayiKoduParameter);
        }
    
        public virtual ObjectResult<OD_SP_AE_KAR_Result> OD_SP_AE_KAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_AE_KAR_Result>("OD_SP_AE_KAR");
        }
    
        public virtual ObjectResult<OD_SP_AEO_ENVANTER_006_Result> OD_SP_AEO_ENVANTER_006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_AEO_ENVANTER_006_Result>("OD_SP_AEO_ENVANTER_006");
        }
    
        public virtual ObjectResult<OD_SP_CihazTakip_Result> OD_SP_CihazTakip(string aramaKelimesi)
        {
            var aramaKelimesiParameter = aramaKelimesi != null ?
                new ObjectParameter("AramaKelimesi", aramaKelimesi) :
                new ObjectParameter("AramaKelimesi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_CihazTakip_Result>("OD_SP_CihazTakip", aramaKelimesiParameter);
        }
    
        public virtual ObjectResult<OD_SP_PRONIST_006_FATURA_Result> OD_SP_PRONIST_006_FATURA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_PRONIST_006_FATURA_Result>("OD_SP_PRONIST_006_FATURA");
        }
    
        public virtual ObjectResult<OD_SP_US_006_01_MALZEME_SONALIMMALIYET_Result> OD_SP_US_006_01_MALZEME_SONALIMMALIYET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OD_SP_US_006_01_MALZEME_SONALIMMALIYET_Result>("OD_SP_US_006_01_MALZEME_SONALIMMALIYET");
        }
    }
}
